name: encite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^0.22.0
  lottie: ^3.3.1
  rive: ^0.13.20
flutter:
  uses-material-design: true

  assets:
    - lib/img/
